name: Python CI

on: push

jobs:

  linting:

    runs-on: ubuntu-latest

    stratergy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        Python-version: ["3.11","3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependecies
        run: |
           pip install flake8

      - name: Run flake8 link
        run: | 
           flake8 .
  testing:
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with : 
          Python-version: ${{matrix.Python-version}}

      - name: Run test
        run: | 
          python -m unittest discover
      